<?php
defined('BASEPATH') OR exit('No direct script access allowed');

/*
|--------------------------------------------------------------------------
| Base Site URL
|--------------------------------------------------------------------------
|
| URL to your CodeIgniter root. Typically this will be your base URL,
| WITH a trailing slash:
|
|	http://example.com/
|
| WARNING: You MUST set this value!
|
| If it is not set, then CodeIgniter will try guess the protocol and path
| your installation, but due to security concerns the hostname will be set
| to $_SERVER['SERVER_ADDR'] if available, or localhost otherwise.
| The auto-detection mechanism exists only for convenience during
| development and MUST NOT be used in production!
|
| If you need to allow multiple domains, remember that this file is still
| a PHP script and you can easily do that on your own.
|
*/
$config['base_url'] = '';

/*
|--------------------------------------------------------------------------
| Index File
|--------------------------------------------------------------------------
|
| Typically this will be your index.php file, unless you've renamed it to
| something else. If you are using mod_rewrite to remove the page set this
| variable so that it is blank.
|
*/
$config['index_page'] = 'index.php';

/*
|--------------------------------------------------------------------------
| URI PROTOCOL
|--------------------------------------------------------------------------
|
| This item determines which server global should be used to retrieve the
| URI string.  The default setting of 'REQUEST_URI' works for most servers.
| If your links do not seem to work, try one of the other delicious flavors:
|
| 'REQUEST_URI'    Uses $_SERVER['REQUEST_URI']
| 'QUERY_STRING'   Uses $_SERVER['QUERY_STRING']
| 'PATH_INFO'      Uses $_SERVER['PATH_INFO']
|
| WARNING: If you set this to 'PATH_INFO', URIs will always be URL-decoded!
*/
$config['uri_protocol']	= 'REQUEST_URI';

/*
|--------------------------------------------------------------------------
| URL suffix
|--------------------------------------------------------------------------
|
| This option allows you to add a suffix to all URLs generated by CodeIgniter.
| For more information please see the user guide:
|
| https://codeigniter.com/user_guide/general/urls.html
*/
$config['url_suffix'] = '';

/*
|--------------------------------------------------------------------------
| Default Language
|--------------------------------------------------------------------------
|
| This determines which set of language files should be used. Make sure
| there is an available translation if you intend to use something other
| than english.
|
*/
$config['language']	= 'english';

/*
|--------------------------------------------------------------------------
| Default Character Set
|--------------------------------------------------------------------------
|
| This determines which character set is used by default in various methods
| that require a character set to be provided.
|
| See http://php.net/htmlspecialchars for a list of supported charsets.
|
*/
$config['charset'] = 'UTF-8';

/*
|--------------------------------------------------------------------------
| Enable/Disable System Hooks
|--------------------------------------------------------------------------
|
| If you would like to use the 'hooks' feature you must enable it by
| setting this variable to TRUE (boolean).  See the user guide for details.
|
*/
$config['enable_hooks'] = FALSE;

/*
|--------------------------------------------------------------------------
| Class Extension Prefix
|--------------------------------------------------------------------------
|
| This item allows you to set the filename/classname prefix when extending
| native libraries.  For more information please see the user guide:
|
| https://codeigniter.com/user_guide/general/core_classes.html
| https://codeigniter.com/user_guide/general/creating_libraries.html
|
*/
$config['subclass_prefix'] = 'MY_';

/*
|--------------------------------------------------------------------------
| Composer auto-loading
|--------------------------------------------------------------------------
|
| Enabling this setting will tell CodeIgniter to look for a Composer
| package auto-loader script in application/vendor/autoload.php.
|
|	$config['composer_autoload'] = TRUE;
|
| Or if you have your vendor/ directory located somewhere else, you
| can opt to set a specific path as well:
|
|	$config['composer_autoload'] = '/path/to/vendor/autoload.php';
|
| For more information about Composer, please visit http://getcomposer.org/
|
| Note: This will NOT disable or override the CodeIgniter-specific
|	autoloading (application/config/autoload.php)
*/
$config['composer_autoload'] = FALSE;

/*
|--------------------------------------------------------------------------
| Allowed URL Characters
|--------------------------------------------------------------------------
|
| This lets you specify which characters are permitted within your URLs.
| When someone tries to submit a URL with disallowed characters they will
| get a warning message.
|
| As a security measure you are STRONGLY encouraged to restrict URLs to
| as few characters as possible.  By default only these are allowed: a-z 0-9~%.:_-
|
| Leave blank to allow all characters -- but only if you are insane.
|
| The configured value is actually a regular expression character group
| and it will be executed as: ! preg_match('/^[<permitted_uri_chars>]+$/i
|
| DO NOT CHANGE THIS UNLESS YOU FULLY UNDERSTAND THE REPERCUSSIONS!!
|
*/
$config['permitted_uri_chars'] = 'a-z 0-9~%.:_\-';

/*
|--------------------------------------------------------------------------
| Enable Query Strings
|--------------------------------------------------------------------------
|
| By default CodeIgniter uses search-engine friendly segment based URLs:
| example.com/who/what/where/
|
| By default CodeIgniter enables access to the $_GET array.  If for some
| reason you would like to disable it, set 'allow_get_array' to FALSE.
|
| You can optionally enable standard query string based URLs:
| example.com?who=me&what=something&where=here
|
| Options are: TRUE or FALSE (boolean)
|
| The other items let you set the query string 'words' that will
| invoke your controllers and its functions:
| example.com/index.php?c=controller&m=function
|
| Please note that some of the helpers won't work as expected when
| this feature is enabled, since CodeIgniter is designed primarily to
| use segment based URLs.
|
*/
$config['allow_get_array'] = TRUE;
$config['enable_query_strings'] = FALSE;
$config['controller_trigger'] = 'c';
$config['function_trigger'] = 'm';
$config['directory_trigger'] = 'd';

/*
|--------------------------------------------------------------------------
| Error Logging Threshold
|--------------------------------------------------------------------------
|
| You can enable error logging by setting a threshold over zero. The
| threshold determines what gets logged. Threshold options are:
|
|	0 = Disables logging, Error logging TURNED OFF
|	1 = Error Messages (including PHP errors)
|	2 = Debug Messages
|	3 = Informational Messages
|	4 = All Messages
|
| You can also pass an array with threshold levels to show individual error types
|
| 	array(2) = Debug Messages, without Error Messages
|
| For a live site you'll usually only enable Errors (1) to be logged otherwise
| your log files will fill up very fast.
|
*/
$config['log_threshold'] = 1;

/*
|--------------------------------------------------------------------------
| Error Logging Directory Path
|--------------------------------------------------------------------------
|
| Leave this BLANK unless you would like to set something other than the default
| application/logs/ directory. Use a full server path with trailing slash.
|
*/
$config['log_path'] = '';

/*
|--------------------------------------------------------------------------
| Log File Extension
|--------------------------------------------------------------------------
|
| The default filename extension for log files. The default 'php' allows for
| protecting the log files via basic scripting, when they are to be stored
| under a publicly accessible directory.
|
| Note: Leaving it blank will default to 'php'.
|
*/
$config['log_file_extension'] = '';

/*
|--------------------------------------------------------------------------
| Log File Permissions
|--------------------------------------------------------------------------
|
| The file system permissions to be applied on newly created log files.
|
| IMPORTANT: This MUST be an integer (no quotes) and you MUST use octal
|            integer notation (i.e. 0700, 0644, etc.)
*/
$config['log_file_permissions'] = 0644;

/*
|--------------------------------------------------------------------------
| Date Format for Logs
|--------------------------------------------------------------------------
|
| Each item that is logged has an associated date. You can use PHP date
| codes to set your own date formatting
|
*/
$config['log_date_format'] = 'Y-m-d H:i:s';

/*
|--------------------------------------------------------------------------
| Error Views Directory Path
|--------------------------------------------------------------------------
|
| Leave this BLANK unless you would like to set something other than the default
| application/views/errors/ directory.  Use a full server path with trailing slash.
|
*/
$config['error_views_path'] = '';

/*
|--------------------------------------------------------------------------
| Cache Directory Path
|--------------------------------------------------------------------------
|
| Leave this BLANK unless you would like to set something other than the default
| application/cache/ directory.  Use a full server path with trailing slash.
|
*/
$config['cache_path'] = '';

/*
|--------------------------------------------------------------------------
| Cache Include Query String
|--------------------------------------------------------------------------
|
| Whether to take the URL query string into consideration when generating
| output cache files. Valid options are:
|
|	FALSE      = Disabled
|	TRUE       = Enabled, take all query parameters into account.
|	             Please be aware that this may result in numerous cache
|	             files generated for the same page over and over again.
|	array('q') = Enabled, but only take into account the specified list
|	             of query parameters.
|
*/
$config['cache_query_string'] = FALSE;

/*
|--------------------------------------------------------------------------
| Encryption Key
|--------------------------------------------------------------------------
|
| If you use the Encryption class, you must set an encryption key.
| See the user guide for more info.
|
| https://codeigniter.com/user_guide/libraries/encryption.html
|
*/
$config['encryption_key'] = '';

/*
|--------------------------------------------------------------------------
| Session Variables
|--------------------------------------------------------------------------
|
| 'sess_driver'
|
|	The storage driver to use: files, database, redis, memcached
|
| 'sess_cookie_name'
|
|	The session cookie name, must contain only [0-9a-z_-] characters
|
| 'sess_expiration'
|
|	The number of SECONDS you want the session to last.
|	Setting to 0 (zero) means expire when the browser is closed.
|
| 'sess_save_path'
|
|	The location to save sessions to, driver dependent.
|
|	For the 'files' driver, it's a path to a writable directory.
|	WARNING: Only absolute paths are supported!
|
|	For the 'database' driver, it's a table name.
|	Please read up the manual for the format with other session drivers.
|
|	IMPORTANT: You are REQUIRED to set a valid save path!
|
| 'sess_match_ip'
|
|	Whether to match the user's IP address when reading the session data.
|
|	WARNING: If you're using the database driver, don't forget to update
|	         your session table's PRIMARY KEY when changing this setting.
|
| 'sess_time_to_update'
|
|	How many seconds between CI regenerating the session ID.
|
| 'sess_regenerate_destroy'
|
|	Whether to destroy session data associated with the old session ID
|	when auto-regenerating the session ID. When set to FALSE, the data
|	will be later deleted by the garbage collector.
|
| Other session cookie settings are shared with the rest of the application,
| except for 'cookie_prefix' and 'cookie_httponly', which are ignored here.
|
*/
$config['sess_driver'] = 'files';
$config['sess_cookie_name'] = 'ci_session';
$config['sess_expiration'] = 7200;
$config['sess_save_path'] = NULL;
$config['sess_match_ip'] = FALSE;
$config['sess_time_to_update'] = 300;
$config['sess_regenerate_destroy'] = FALSE;

/*
|--------------------------------------------------------------------------
| Cookie Related Variables
|--------------------------------------------------------------------------
|
| 'cookie_prefix'   = Set a cookie name prefix if you need to avoid collisions
| 'cookie_domain'   = Set to .your-domain.com for site-wide cookies
| 'cookie_path'     = Typically will be a forward slash
| 'cookie_secure'   = Cookie will only be set if a secure HTTPS connection exists.
| 'cookie_httponly' = Cookie will only be accessible via HTTP(S) (no javascript)
|
| Note: These settings (with the exception of 'cookie_prefix' and
|       'cookie_httponly') will also affect sessions.
|
*/
$config['cookie_prefix']	= '';
$config['cookie_domain']	= '';
$config['cookie_path']		= '/';
$config['cookie_secure']	= FALSE;
$config['cookie_httponly'] 	= FALSE;

/*
|--------------------------------------------------------------------------
| Standardize newlines
|--------------------------------------------------------------------------
|
| Determines whether to standardize newline characters in input data,
| meaning to replace \r\n, \r, \n occurrences with the PHP_EOL value.
|
| This is particularly useful for portability between UNIX-based OSes,
| (usually \n) and Windows (\r\n).
|
*/
$config['standardize_newlines'] = FALSE;

/*
|--------------------------------------------------------------------------
| Global XSS Filtering
|--------------------------------------------------------------------------
|
| Determines whether the XSS filter is always active when GET, POST or
| COOKIE data is encountered
|
| WARNING: This feature is DEPRECATED and currently available only
|          for backwards compatibility purposes!
|
*/
$config['global_xss_filtering'] = FALSE;

/*
|--------------------------------------------------------------------------
| Cross Site Request Forgery
|--------------------------------------------------------------------------
| Enables a CSRF cookie token to be set. When set to TRUE, token will be
| checked on a submitted form. If you are accepting user data, it is strongly
| recommended CSRF protection be enabled.
|
| 'csrf_token_name' = The token name
| 'csrf_cookie_name' = The cookie name
| 'csrf_expire' = The number in seconds the token should expire.
| 'csrf_regenerate' = Regenerate token on every submission
| 'csrf_exclude_uris' = Array of URIs which ignore CSRF checks
*/
$config['csrf_protection'] = FALSE;
$config['csrf_token_name'] = 'csrf_test_name';
$config['csrf_cookie_name'] = 'csrf_cookie_name';
$config['csrf_expire'] = 7200;
$config['csrf_regenerate'] = TRUE;
$config['csrf_exclude_uris'] = array();

/*
|--------------------------------------------------------------------------
| Output Compression
|--------------------------------------------------------------------------
|
| Enables Gzip output compression for faster page loads.  When enabled,
| the output class will test whether your server supports Gzip.
| Even if it does, however, not all browsers support compression
| so enable only if you are reasonably sure your visitors can handle it.
|
| Only used if zlib.output_compression is turned off in your php.ini.
| Please do not use it together with httpd-level output compression.
|
| VERY IMPORTANT:  If you are getting a blank page when compression is enabled it
| means you are prematurely outputting something to your browser. It could
| even be a line of whitespace at the end of one of your scripts.  For
| compression to work, nothing can be sent before the output buffer is called
| by the output class.  Do not 'echo' any values with compression enabled.
|
*/
$config['compress_output'] = FALSE;

/*
|--------------------------------------------------------------------------
| Master Time Reference
|--------------------------------------------------------------------------
|
| Options are 'local' or any PHP supported timezone. This preference tells
| the system whether to use your server's local time as the master 'now'
| reference, or convert it to the configured one timezone. See the 'date
| helper' page of the user guide for information regarding date handling.
|
*/
$config['time_reference'] = 'local';

/*
|--------------------------------------------------------------------------
| Rewrite PHP Short Tags
|--------------------------------------------------------------------------
|
| If your PHP installation does not have short tag support enabled CI
| can rewrite the tags on-the-fly, enabling you to utilize that syntax
| in your view files.  Options are TRUE or FALSE (boolean)
|
| Note: You need to have eval() enabled for this to work.
|
*/
$config['rewrite_short_tags'] = FALSE;

/*
|--------------------------------------------------------------------------
| Reverse Proxy IPs
|--------------------------------------------------------------------------
|
| If your server is behind a reverse proxy, you must whitelist the proxy
| IP addresses from which CodeIgniter should trust headers such as
| HTTP_X_FORWARDED_FOR and HTTP_CLIENT_IP in order to properly identify
| the visitor's IP address.
|
| You can use both an array or a comma-separated list of proxy addresses,
| as well as specifying whole subnets. Here are a few examples:
|
| Comma-separated:	'10.0.1.200,192.168.5.0/24'
| Array:		array('10.0.1.200', '192.168.5.0/24')
*/
$config['proxy_ips'] = '';

$config['daigou'] = '代购,香港,HK,Hong Kong,hk';

$config['at'] = '关注,好友,添加,王琳玲,方航,琰琰';

$config['news'] = '资讯,news,NEWS';

$config['express_list'] = array (
  '澳大利亚邮政' => 'auspost',
  'AAE' => 'aae',
  'aae' => 'aae',
  '安信达' => 'anxindakuaixi',
  '汇通' => 'huitongkuaidi',
  '百福东方' => 'baifudongfang',
  'BHT' => 'bht',
  'bht' => 'bht',
  '邦送' => 'bangsongwuliu',
  '希伊艾斯' => 'cces',
  '中国东方' => 'coe',
  '传喜' => 'chuanxiwuliu',
  '加拿大邮政' => 'canpostfr',
  '大田' => 'datianwuliu',
  '德邦' => 'debangwuliu',
  'DPEX' => 'dpex',
  'dpex' => 'dpex',
  'DHL' => 'dhl',
  'dhl' => 'dhl',
  'D速' => 'dsukuaidi',
  'd速' => 'dsukuaidi',
  '递四方' => 'disifang',
  'E邮宝' => 'ems',
  'e邮宝' => 'ems',
  'EMS' => 'emsen',
  'ems' => 'emsen',
  'Fedex' => 'fedexus',
  'FEDEX' => 'fedexus',
  'fedex' => 'fedexus',
  '飞康达' => 'feikangda',
  '飞快达' => 'feikuaida',
  '如风达' => 'rufengda',
  '风行天下' => 'fengxingtianxia',
  '飞豹' => 'feibaokuaidi',
  '港中能达' => 'ganzhongnengda',
  '国通' => 'guotongkuaidi',
  '广东邮政' => 'guangdongyouzhengwuliu',
  'GLS' => 'gls',
  'gls' => 'gls',
  '共速达' => 'gongsuda',
  '汇强' => 'huiqiangkuaidi',
  '天地华宇' => 'tiandihuayu',
  '恒路' => 'hengluwuliu',
  '华夏龙' => 'huaxialongwuliu',
  '天天' => 'tiantian',
  '海外环球' => 'haiwaihuanqiu',
  '河北建华' => 'hebeijianhua',
  '海盟' => 'haimengsudi',
  '华企' => 'huaqikuaiyun',
  '山东海红' => 'haihongwangsong',
  '佳吉' => 'jiajiwuliu',
  '佳怡' => 'jiayiwuliu',
  '加运美' => 'jiayunmeiwuliu',
  '京广' => 'jinguangsudikuaijian',
  '急先达' => 'jixianda',
  '晋越' => 'jinyuekuaidi',
  '捷特' => 'jietekuaidi',
  '金大' => 'jindawuliu',
  '嘉里大通' => 'jialidatong',
  '快捷' => 'kuaijiesudi',
  '康力' => 'kangliwuliu',
  '跨越' => 'kuayue',
  '联昊通' => 'lianhaowuliu',
  '龙邦' => 'longbanwuliu',
  '蓝镖' => 'lanbiaokuaidi',
  '乐捷递' => 'lejiedi',
  '联邦' => 'lianbangkuaidien',
  '立即送' => 'lijisong',
  '隆浪' => 'longlangkuaidi',
  '门对门' => 'menduimen',
  '美国' => 'meiguokuaidi',
  '明亮' => 'mingliangwuliu',
  'OCS' => 'ocs',
  'ocs' => 'ocs',
  'onTrac' => 'ontrac',
  'ontrac' => 'ontrac',
  '全晨' => 'quanchenkuaidi',
  '全际通' => 'quanjitong',
  '全日通' => 'quanritongkuaidi',
  '全一' => 'quanyikuaidi',
  '全峰' => 'quanfengkuaidi',
  '七天连锁' => 'sevendays',
  '申通' => 'shentong',
  '顺丰' => 'shunfengen',
  '三态' => 'santaisudi',
  '盛辉' => 'shenghuiwuliu',
  '速尔' => 'suer',
  '盛丰' => 'shengfengwuliu',
  '上大' => 'shangda',
  '赛澳递' => 'saiaodi',
  '山西红马甲' => 'sxhongmajia',
  '圣安' => 'shenganwuliu',
  '穗佳' => 'suijiawuliu',
  'TNT' => 'tnten',
  '通和天下' => 'tonghetianxia',
  'UPS' => 'upsen',
  'ups' => 'upsen',
  '优速' => 'youshuwuliu',
  'USPS' => 'usps',
  'usps' => 'usps',
  '万家' => 'wanjiawuliu',
  '万象' => 'wanxiangwuliu',
  '微特派' => 'weitepai',
  '新邦' => 'xinbangwuliu',
  '信丰' => 'xinfengwuliu',
  '星晨急便' => 'xingchengjibian',
  '鑫飞鸿' => 'xinhongyukuaidi',
  '新蛋奥硕' => 'neweggozzo',
  '香港邮政' => 'hkpost',
  '圆通' => 'yuantong',
  '韵达' => 'yunda',
  '运通' => 'yuntongkuaidi',
  '远成' => 'yuanchengwuliu',
  '亚风' => 'yafengsudi',
  '一邦' => 'yibangwuliu',
  '源伟丰' => 'yuanweifeng',
  '元智捷诚' => 'yuanzhijiecheng',
  '越丰' => 'yuefengwuliu',
  '源安达' => 'yuananda',
  '原飞航' => 'yuanfeihangwuliu',
  '忠信达' => 'zhongxinda',
  '芝麻开门' => 'zhimakaimen',
  '银捷' => 'yinjiesudi',
  '一统飞鸿' => 'yitongfeihong',
  '中通' => 'zhongtong',
  '宅急送' => 'zhaijisong',
  '中邮' => 'zhongyouwuliu',
  '中速' => 'zhongsukuaidi',
  '郑州建华' => 'zhengzhoujianhua',
  '中天万运' => 'zhongtianwanyun',
);

$config['city'] = array(
  '北京' => 101010100,
  '朝阳' => 101071201,
  '顺义' => 101010400,
  '怀柔' => 101010500,
  '通州' => 101010600,
  '昌平' => 101010700,
  '延庆' => 101010800,
  '丰台' => 101010900,
  '石景山' => 101011000,
  '大兴' => 101011100,
  '房山' => 101011200,
  '密云' => 101011300,
  '门头沟' => 101011400,
  '平谷' => 101011500,
  '八达岭' => 101011600,
  '佛爷顶' => 101011700,
  '汤河口' => 101011800,
  '密云上甸子' => 101011900,
  '斋堂' => 101012000,
  '霞云岭' => 101012100,
  '北京城区' => 101012200,
  '海淀' => 101010200,
  '天津' => 101030100,
  '宝坻' => 101030300,
  '东丽' => 101030400,
  '西青' => 101030500,
  '北辰' => 101030600,
  '蓟县' => 101031400,
  '汉沽' => 101030800,
  '静海' => 101030900,
  '津南' => 101031000,
  '塘沽' => 101031100,
  '大港' => 101031200,
  '武清' => 101030200,
  '宁河' => 101030700,
  '上海' => 101020100,
  '宝山' => 101020300,
  '嘉定' => 101020500,
  '南汇' => 101020600,
  '浦东' => 101021300,
  '青浦' => 101020800,
  '松江' => 101020900,
  '奉贤' => 101021000,
  '崇明' => 101021100,
  '徐家汇' => 101021200,
  '闵行' => 101020200,
  '金山' => 101020700,
  '石家庄' => 101090101,
  '张家口' => 101090301,
  '承德' => 101090402,
  '唐山' => 101090501,
  '秦皇岛' => 101091101,
  '沧州' => 101090701,
  '衡水' => 101090801,
  '邢台' => 101090901,
  '邯郸' => 101091001,
  '保定' => 101090201,
  '廊坊' => 101090601,
  '郑州' => 101180101,
  '新乡' => 101180301,
  '许昌' => 101180401,
  '平顶山' => 101180501,
  '信阳' => 101180601,
  '南阳' => 101180701,
  '开封' => 101180801,
  '洛阳' => 101180901,
  '商丘' => 101181001,
  '焦作' => 101181101,
  '鹤壁' => 101181201,
  '濮阳' => 101181301,
  '周口' => 101181401,
  '漯河' => 101181501,
  '驻马店' => 101181601,
  '三门峡' => 101181701,
  '济源' => 101181801,
  '安阳' => 101180201,
  '合肥' => 101220101,
  '芜湖' => 101220301,
  '淮南' => 101220401,
  '马鞍山' => 101220501,
  '安庆' => 101220601,
  '宿州' => 101220701,
  '阜阳' => 101220801,
  '亳州' => 101220901,
  '黄山' => 101221001,
  '滁州' => 101221101,
  '淮北' => 101221201,
  '铜陵' => 101221301,
  '宣城' => 101221401,
  '六安' => 101221501,
  '巢湖' => 101221601,
  '池州' => 101221701,
  '蚌埠' => 101220201,
  '杭州' => 101210101,
  '舟山' => 101211101,
  '湖州' => 101210201,
  '嘉兴' => 101210301,
  '金华' => 101210901,
  '绍兴' => 101210501,
  '台州' => 101210601,
  '温州' => 101210701,
  '丽水' => 101210801,
  '衢州' => 101211001,
  '宁波' => 101210401,
  '重庆' => 101040100,
  '合川' => 101040300,
  '南川' => 101040400,
  '江津' => 101040500,
  '万盛' => 101040600,
  '渝北' => 101040700,
  '北碚' => 101040800,
  '巴南' => 101040900,
  '长寿' => 101041000,
  '黔江' => 101041100,
  '万州天城' => 101041200,
  '万州龙宝' => 101041300,
  '涪陵' => 101041400,
  '开县' => 101041500,
  '城口' => 101041600,
  '云阳' => 101041700,
  '巫溪' => 101041800,
  '奉节' => 101041900,
  '巫山' => 101042000,
  '潼南' => 101042100,
  '垫江' => 101042200,
  '梁平' => 101042300,
  '忠县' => 101042400,
  '石柱' => 101042500,
  '大足' => 101042600,
  '荣昌' => 101042700,
  '铜梁' => 101042800,
  '璧山' => 101042900,
  '丰都' => 101043000,
  '武隆' => 101043100,
  '彭水' => 101043200,
  '綦江' => 101043300,
  '酉阳' => 101043400,
  '秀山' => 101043600,
  '沙坪坝' => 101043700,
  '永川' => 101040200,
  '福州' => 101230101,
  '泉州' => 101230501,
  '漳州' => 101230601,
  '龙岩' => 101230701,
  '晋江' => 101230509,
  '南平' => 101230901,
  '厦门' => 101230201,
  '宁德' => 101230301,
  '莆田' => 101230401,
  '三明' => 101230801,
  '兰州' => 101160101,
  '平凉' => 101160301,
  '庆阳' => 101160401,
  '武威' => 101160501,
  '金昌' => 101160601,
  '嘉峪关' => 101161401,
  '酒泉' => 101160801,
  '天水' => 101160901,
  '武都' => 101161001,
  '临夏' => 101161101,
  '合作' => 101161201,
  '白银' => 101161301,
  '定西' => 101160201,
  '张掖' => 101160701,
  '广州' => 101280101,
  '惠州' => 101280301,
  '梅州' => 101280401,
  '汕头' => 101280501,
  '深圳' => 101280601,
  '珠海' => 101280701,
  '佛山' => 101280800,
  '肇庆' => 101280901,
  '湛江' => 101281001,
  '江门' => 101281101,
  '河源' => 101281201,
  '清远' => 101281301,
  '云浮' => 101281401,
  '潮州' => 101281501,
  '东莞' => 101281601,
  '中山' => 101281701,
  '阳江' => 101281801,
  '揭阳' => 101281901,
  '茂名' => 101282001,
  '汕尾' => 101282101,
  '韶关' => 101280201,
  '南宁' => 101300101,
  '柳州' => 101300301,
  '来宾' => 101300401,
  '桂林' => 101300501,
  '梧州' => 101300601,
  '防城港' => 101301401,
  '贵港' => 101300801,
  '玉林' => 101300901,
  '百色' => 101301001,
  '钦州' => 101301101,
  '河池' => 101301201,
  '北海' => 101301301,
  '崇左' => 101300201,
  '贺州' => 101300701,
  '贵阳' => 101260101,
  '安顺' => 101260301,
  '都匀' => 101260401,
  '兴义' => 101260906,
  '铜仁' => 101260601,
  '毕节' => 101260701,
  '六盘水' => 101260801,
  '遵义' => 101260201,
  '凯里' => 101260501,
  '昆明' => 101290101,
  '红河' => 101290301,
  '文山' => 101290601,
  '玉溪' => 101290701,
  '楚雄' => 101290801,
  '普洱' => 101290901,
  '昭通' => 101291001,
  '临沧' => 101291101,
  '怒江' => 101291201,
  '香格里拉' => 101291301,
  '丽江' => 101291401,
  '德宏' => 101291501,
  '景洪' => 101291601,
  '大理' => 101290201,
  '曲靖' => 101290401,
  '保山' => 101290501,
  '呼和浩特' => 101080101,
  '乌海' => 101080301,
  '集宁' => 101080401,
  '通辽' => 101080501,
  '阿拉善左旗' => 101081201,
  '鄂尔多斯' => 101080701,
  '临河' => 101080801,
  '锡林浩特' => 101080901,
  '呼伦贝尔' => 101081000,
  '乌兰浩特' => 101081101,
  '包头' => 101080201,
  '赤峰' => 101080601,
  '南昌' => 101240101,
  '上饶' => 101240301,
  '抚州' => 101240401,
  '宜春' => 101240501,
  '鹰潭' => 101241101,
  '赣州' => 101240701,
  '景德镇' => 101240801,
  '萍乡' => 101240901,
  '新余' => 101241001,
  '九江' => 101240201,
  '吉安' => 101240601,
  '武汉' => 101200101,
  '黄冈' => 101200501,
  '荆州' => 101200801,
  '宜昌' => 101200901,
  '恩施' => 101201001,
  '十堰' => 101201101,
  '神农架' => 101201201,
  '随州' => 101201301,
  '荆门' => 101201401,
  '天门' => 101201501,
  '仙桃' => 101201601,
  '潜江' => 101201701,
  '襄樊' => 101200201,
  '鄂州' => 101200301,
  '孝感' => 101200401,
  '黄石' => 101200601,
  '咸宁' => 101200701,
  '成都' => 101270101,
  '自贡' => 101270301,
  '绵阳' => 101270401,
  '南充' => 101270501,
  '达州' => 101270601,
  '遂宁' => 101270701,
  '广安' => 101270801,
  '巴中' => 101270901,
  '泸州' => 101271001,
  '宜宾' => 101271101,
  '内江' => 101271201,
  '资阳' => 101271301,
  '乐山' => 101271401,
  '眉山' => 101271501,
  '凉山' => 101271601,
  '雅安' => 101271701,
  '甘孜' => 101271801,
  '阿坝' => 101271901,
  '德阳' => 101272001,
  '广元' => 101272101,
  '攀枝花' => 101270201,
  '银川' => 101170101,
  '中卫' => 101170501,
  '固原' => 101170401,
  '石嘴山' => 101170201,
  '吴忠' => 101170301,
  '西宁' => 101150101,
  '黄南' => 101150301,
  '海北' => 101150801,
  '果洛' => 101150501,
  '玉树' => 101150601,
  '海西' => 101150701,
  '海东' => 101150201,
  '海南' => 101150401,
  '济南' => 101120101,
  '潍坊' => 101120601,
  '临沂' => 101120901,
  '菏泽' => 101121001,
  '滨州' => 101121101,
  '东营' => 101121201,
  '威海' => 101121301,
  '枣庄' => 101121401,
  '日照' => 101121501,
  '莱芜' => 101121601,
  '聊城' => 101121701,
  '青岛' => 101120201,
  '淄博' => 101120301,
  '德州' => 101120401,
  '烟台' => 101120501,
  '济宁' => 101120701,
  '泰安' => 101120801,
  '西安' => 101110101,
  '延安' => 101110300,
  '榆林' => 101110401,
  '铜川' => 101111001,
  '商洛' => 101110601,
  '安康' => 101110701,
  '汉中' => 101110801,
  '宝鸡' => 101110901,
  '咸阳' => 101110200,
  '渭南' => 101110501,
  '太原' => 101100101,
  '临汾' => 101100701,
  '运城' => 101100801,
  '朔州' => 101100901,
  '忻州' => 101101001,
  '长治' => 101100501,
  '大同' => 101100201,
  '阳泉' => 101100301,
  '晋中' => 101100401,
  '晋城' => 101100601,
  '吕梁' => 101101100,
  '乌鲁木齐' => 101130101,
  '石河子' => 101130301,
  '昌吉' => 101130401,
  '吐鲁番' => 101130501,
  '库尔勒' => 101130601,
  '阿拉尔' => 101130701,
  '阿克苏' => 101130801,
  '喀什' => 101130901,
  '伊宁' => 101131001,
  '塔城' => 101131101,
  '哈密' => 101131201,
  '和田' => 101131301,
  '阿勒泰' => 101131401,
  '阿图什' => 101131501,
  '博乐' => 101131601,
  '克拉玛依' => 101130201,
  '拉萨' => 101140101,
  '山南' => 101140301,
  '阿里' => 101140701,
  '昌都' => 101140501,
  '那曲' => 101140601,
  '日喀则' => 101140201,
  '林芝' => 101140401,
  '台北县' => 101340101,
  '高雄' => 101340201,
  '台中' => 101340401,
  '海口' => 101310101,
  '三亚' => 101310201,
  '东方' => 101310202,
  '临高' => 101310203,
  '澄迈' => 101310204,
  '儋州' => 101310205,
  '昌江' => 101310206,
  '白沙' => 101310207,
  '琼中' => 101310208,
  '定安' => 101310209,
  '屯昌' => 101310210,
  '琼海' => 101310211,
  '文昌' => 101310212,
  '保亭' => 101310214,
  '万宁' => 101310215,
  '陵水' => 101310216,
  '西沙' => 101310217,
  '南沙岛' => 101310220,
  '乐东' => 101310221,
  '五指山' => 101310222,
  '琼山' => 101310102,
  '长沙' => 101250101,
  '株洲' => 101250301,
  '衡阳' => 101250401,
  '郴州' => 101250501,
  '常德' => 101250601,
  '益阳' => 101250700,
  '娄底' => 101250801,
  '邵阳' => 101250901,
  '岳阳' => 101251001,
  '张家界' => 101251101,
  '怀化' => 101251201,
  '黔阳' => 101251301,
  '永州' => 101251401,
  '吉首' => 101251501,
  '湘潭' => 101250201,
  '南京' => 101190101,
  '镇江' => 101190301,
  '苏州' => 101190401,
  '南通' => 101190501,
  '扬州' => 101190601,
  '宿迁' => 101191301,
  '徐州' => 101190801,
  '淮安' => 101190901,
  '连云港' => 101191001,
  '常州' => 101191101,
  '泰州' => 101191201,
  '无锡' => 101190201,
  '盐城' => 101190701,
  '哈尔滨' => 101050101,
  '牡丹江' => 101050301,
  '佳木斯' => 101050401,
  '绥化' => 101050501,
  '黑河' => 101050601,
  '双鸭山' => 101051301,
  '伊春' => 101050801,
  '大庆' => 101050901,
  '七台河' => 101051002,
  '鸡西' => 101051101,
  '鹤岗' => 101051201,
  '齐齐哈尔' => 101050201,
  '大兴安岭' => 101050701,
  '长春' => 101060101,
  '延吉' => 101060301,
  '四平' => 101060401,
  '白山' => 101060901,
  '白城' => 101060601,
  '辽源' => 101060701,
  '松原' => 101060801,
  '吉林' => 101060201,
  '通化' => 101060501,
  '沈阳' => 101070101,
  '鞍山' => 101070301,
  '抚顺' => 101070401,
  '本溪' => 101070501,
  '丹东' => 101070601,
  '葫芦岛' => 101071401,
  '营口' => 101070801,
  '阜新' => 101070901,
  '辽阳' => 101071001,
  '铁岭' => 101071101,
  '盘锦' => 101071301,
  '大连' => 101070201,
  '锦州' => 101070701,
);