<?php
defined('BASEPATH') OR exit('No direct script access allowed');

/*
|--------------------------------------------------------------------------
| Base Site URL
|--------------------------------------------------------------------------
|
| URL to your CodeIgniter root. Typically this will be your base URL,
| WITH a trailing slash:
|
|	http://example.com/
|
| WARNING: You MUST set this value!
|
| If it is not set, then CodeIgniter will try guess the protocol and path
| your installation, but due to security concerns the hostname will be set
| to $_SERVER['SERVER_ADDR'] if available, or localhost otherwise.
| The auto-detection mechanism exists only for convenience during
| development and MUST NOT be used in production!
|
| If you need to allow multiple domains, remember that this file is still
| a PHP script and you can easily do that on your own.
|
*/
$config['base_url'] = '';

/*
|--------------------------------------------------------------------------
| Index File
|--------------------------------------------------------------------------
|
| Typically this will be your index.php file, unless you've renamed it to
| something else. If you are using mod_rewrite to remove the page set this
| variable so that it is blank.
|
*/
$config['index_page'] = 'index.php';

/*
|--------------------------------------------------------------------------
| URI PROTOCOL
|--------------------------------------------------------------------------
|
| This item determines which server global should be used to retrieve the
| URI string.  The default setting of 'REQUEST_URI' works for most servers.
| If your links do not seem to work, try one of the other delicious flavors:
|
| 'REQUEST_URI'    Uses $_SERVER['REQUEST_URI']
| 'QUERY_STRING'   Uses $_SERVER['QUERY_STRING']
| 'PATH_INFO'      Uses $_SERVER['PATH_INFO']
|
| WARNING: If you set this to 'PATH_INFO', URIs will always be URL-decoded!
*/
$config['uri_protocol']	= 'REQUEST_URI';

/*
|--------------------------------------------------------------------------
| URL suffix
|--------------------------------------------------------------------------
|
| This option allows you to add a suffix to all URLs generated by CodeIgniter.
| For more information please see the user guide:
|
| https://codeigniter.com/user_guide/general/urls.html
*/
$config['url_suffix'] = '';

/*
|--------------------------------------------------------------------------
| Default Language
|--------------------------------------------------------------------------
|
| This determines which set of language files should be used. Make sure
| there is an available translation if you intend to use something other
| than english.
|
*/
$config['language']	= 'english';

/*
|--------------------------------------------------------------------------
| Default Character Set
|--------------------------------------------------------------------------
|
| This determines which character set is used by default in various methods
| that require a character set to be provided.
|
| See http://php.net/htmlspecialchars for a list of supported charsets.
|
*/
$config['charset'] = 'UTF-8';

/*
|--------------------------------------------------------------------------
| Enable/Disable System Hooks
|--------------------------------------------------------------------------
|
| If you would like to use the 'hooks' feature you must enable it by
| setting this variable to TRUE (boolean).  See the user guide for details.
|
*/
$config['enable_hooks'] = FALSE;

/*
|--------------------------------------------------------------------------
| Class Extension Prefix
|--------------------------------------------------------------------------
|
| This item allows you to set the filename/classname prefix when extending
| native libraries.  For more information please see the user guide:
|
| https://codeigniter.com/user_guide/general/core_classes.html
| https://codeigniter.com/user_guide/general/creating_libraries.html
|
*/
$config['subclass_prefix'] = 'MY_';

/*
|--------------------------------------------------------------------------
| Composer auto-loading
|--------------------------------------------------------------------------
|
| Enabling this setting will tell CodeIgniter to look for a Composer
| package auto-loader script in application/vendor/autoload.php.
|
|	$config['composer_autoload'] = TRUE;
|
| Or if you have your vendor/ directory located somewhere else, you
| can opt to set a specific path as well:
|
|	$config['composer_autoload'] = '/path/to/vendor/autoload.php';
|
| For more information about Composer, please visit http://getcomposer.org/
|
| Note: This will NOT disable or override the CodeIgniter-specific
|	autoloading (application/config/autoload.php)
*/
$config['composer_autoload'] = FALSE;

/*
|--------------------------------------------------------------------------
| Allowed URL Characters
|--------------------------------------------------------------------------
|
| This lets you specify which characters are permitted within your URLs.
| When someone tries to submit a URL with disallowed characters they will
| get a warning message.
|
| As a security measure you are STRONGLY encouraged to restrict URLs to
| as few characters as possible.  By default only these are allowed: a-z 0-9~%.:_-
|
| Leave blank to allow all characters -- but only if you are insane.
|
| The configured value is actually a regular expression character group
| and it will be executed as: ! preg_match('/^[<permitted_uri_chars>]+$/i
|
| DO NOT CHANGE THIS UNLESS YOU FULLY UNDERSTAND THE REPERCUSSIONS!!
|
*/
$config['permitted_uri_chars'] = 'a-z 0-9~%.:_\-';

/*
|--------------------------------------------------------------------------
| Enable Query Strings
|--------------------------------------------------------------------------
|
| By default CodeIgniter uses search-engine friendly segment based URLs:
| example.com/who/what/where/
|
| By default CodeIgniter enables access to the $_GET array.  If for some
| reason you would like to disable it, set 'allow_get_array' to FALSE.
|
| You can optionally enable standard query string based URLs:
| example.com?who=me&what=something&where=here
|
| Options are: TRUE or FALSE (boolean)
|
| The other items let you set the query string 'words' that will
| invoke your controllers and its functions:
| example.com/index.php?c=controller&m=function
|
| Please note that some of the helpers won't work as expected when
| this feature is enabled, since CodeIgniter is designed primarily to
| use segment based URLs.
|
*/
$config['allow_get_array'] = TRUE;
$config['enable_query_strings'] = FALSE;
$config['controller_trigger'] = 'c';
$config['function_trigger'] = 'm';
$config['directory_trigger'] = 'd';

/*
|--------------------------------------------------------------------------
| Error Logging Threshold
|--------------------------------------------------------------------------
|
| You can enable error logging by setting a threshold over zero. The
| threshold determines what gets logged. Threshold options are:
|
|	0 = Disables logging, Error logging TURNED OFF
|	1 = Error Messages (including PHP errors)
|	2 = Debug Messages
|	3 = Informational Messages
|	4 = All Messages
|
| You can also pass an array with threshold levels to show individual error types
|
| 	array(2) = Debug Messages, without Error Messages
|
| For a live site you'll usually only enable Errors (1) to be logged otherwise
| your log files will fill up very fast.
|
*/
$config['log_threshold'] = 1;

/*
|--------------------------------------------------------------------------
| Error Logging Directory Path
|--------------------------------------------------------------------------
|
| Leave this BLANK unless you would like to set something other than the default
| application/logs/ directory. Use a full server path with trailing slash.
|
*/
$config['log_path'] = '';

/*
|--------------------------------------------------------------------------
| Log File Extension
|--------------------------------------------------------------------------
|
| The default filename extension for log files. The default 'php' allows for
| protecting the log files via basic scripting, when they are to be stored
| under a publicly accessible directory.
|
| Note: Leaving it blank will default to 'php'.
|
*/
$config['log_file_extension'] = '';

/*
|--------------------------------------------------------------------------
| Log File Permissions
|--------------------------------------------------------------------------
|
| The file system permissions to be applied on newly created log files.
|
| IMPORTANT: This MUST be an integer (no quotes) and you MUST use octal
|            integer notation (i.e. 0700, 0644, etc.)
*/
$config['log_file_permissions'] = 0644;

/*
|--------------------------------------------------------------------------
| Date Format for Logs
|--------------------------------------------------------------------------
|
| Each item that is logged has an associated date. You can use PHP date
| codes to set your own date formatting
|
*/
$config['log_date_format'] = 'Y-m-d H:i:s';

/*
|--------------------------------------------------------------------------
| Error Views Directory Path
|--------------------------------------------------------------------------
|
| Leave this BLANK unless you would like to set something other than the default
| application/views/errors/ directory.  Use a full server path with trailing slash.
|
*/
$config['error_views_path'] = '';

/*
|--------------------------------------------------------------------------
| Cache Directory Path
|--------------------------------------------------------------------------
|
| Leave this BLANK unless you would like to set something other than the default
| application/cache/ directory.  Use a full server path with trailing slash.
|
*/
$config['cache_path'] = '';

/*
|--------------------------------------------------------------------------
| Cache Include Query String
|--------------------------------------------------------------------------
|
| Whether to take the URL query string into consideration when generating
| output cache files. Valid options are:
|
|	FALSE      = Disabled
|	TRUE       = Enabled, take all query parameters into account.
|	             Please be aware that this may result in numerous cache
|	             files generated for the same page over and over again.
|	array('q') = Enabled, but only take into account the specified list
|	             of query parameters.
|
*/
$config['cache_query_string'] = FALSE;

/*
|--------------------------------------------------------------------------
| Encryption Key
|--------------------------------------------------------------------------
|
| If you use the Encryption class, you must set an encryption key.
| See the user guide for more info.
|
| https://codeigniter.com/user_guide/libraries/encryption.html
|
*/
$config['encryption_key'] = '';

/*
|--------------------------------------------------------------------------
| Session Variables
|--------------------------------------------------------------------------
|
| 'sess_driver'
|
|	The storage driver to use: files, database, redis, memcached
|
| 'sess_cookie_name'
|
|	The session cookie name, must contain only [0-9a-z_-] characters
|
| 'sess_expiration'
|
|	The number of SECONDS you want the session to last.
|	Setting to 0 (zero) means expire when the browser is closed.
|
| 'sess_save_path'
|
|	The location to save sessions to, driver dependent.
|
|	For the 'files' driver, it's a path to a writable directory.
|	WARNING: Only absolute paths are supported!
|
|	For the 'database' driver, it's a table name.
|	Please read up the manual for the format with other session drivers.
|
|	IMPORTANT: You are REQUIRED to set a valid save path!
|
| 'sess_match_ip'
|
|	Whether to match the user's IP address when reading the session data.
|
|	WARNING: If you're using the database driver, don't forget to update
|	         your session table's PRIMARY KEY when changing this setting.
|
| 'sess_time_to_update'
|
|	How many seconds between CI regenerating the session ID.
|
| 'sess_regenerate_destroy'
|
|	Whether to destroy session data associated with the old session ID
|	when auto-regenerating the session ID. When set to FALSE, the data
|	will be later deleted by the garbage collector.
|
| Other session cookie settings are shared with the rest of the application,
| except for 'cookie_prefix' and 'cookie_httponly', which are ignored here.
|
*/
$config['sess_driver'] = 'files';
$config['sess_cookie_name'] = 'ci_session';
$config['sess_expiration'] = 7200;
$config['sess_save_path'] = NULL;
$config['sess_match_ip'] = FALSE;
$config['sess_time_to_update'] = 300;
$config['sess_regenerate_destroy'] = FALSE;

/*
|--------------------------------------------------------------------------
| Cookie Related Variables
|--------------------------------------------------------------------------
|
| 'cookie_prefix'   = Set a cookie name prefix if you need to avoid collisions
| 'cookie_domain'   = Set to .your-domain.com for site-wide cookies
| 'cookie_path'     = Typically will be a forward slash
| 'cookie_secure'   = Cookie will only be set if a secure HTTPS connection exists.
| 'cookie_httponly' = Cookie will only be accessible via HTTP(S) (no javascript)
|
| Note: These settings (with the exception of 'cookie_prefix' and
|       'cookie_httponly') will also affect sessions.
|
*/
$config['cookie_prefix']	= '';
$config['cookie_domain']	= '';
$config['cookie_path']		= '/';
$config['cookie_secure']	= FALSE;
$config['cookie_httponly'] 	= FALSE;

/*
|--------------------------------------------------------------------------
| Standardize newlines
|--------------------------------------------------------------------------
|
| Determines whether to standardize newline characters in input data,
| meaning to replace \r\n, \r, \n occurrences with the PHP_EOL value.
|
| This is particularly useful for portability between UNIX-based OSes,
| (usually \n) and Windows (\r\n).
|
*/
$config['standardize_newlines'] = FALSE;

/*
|--------------------------------------------------------------------------
| Global XSS Filtering
|--------------------------------------------------------------------------
|
| Determines whether the XSS filter is always active when GET, POST or
| COOKIE data is encountered
|
| WARNING: This feature is DEPRECATED and currently available only
|          for backwards compatibility purposes!
|
*/
$config['global_xss_filtering'] = FALSE;

/*
|--------------------------------------------------------------------------
| Cross Site Request Forgery
|--------------------------------------------------------------------------
| Enables a CSRF cookie token to be set. When set to TRUE, token will be
| checked on a submitted form. If you are accepting user data, it is strongly
| recommended CSRF protection be enabled.
|
| 'csrf_token_name' = The token name
| 'csrf_cookie_name' = The cookie name
| 'csrf_expire' = The number in seconds the token should expire.
| 'csrf_regenerate' = Regenerate token on every submission
| 'csrf_exclude_uris' = Array of URIs which ignore CSRF checks
*/
$config['csrf_protection'] = FALSE;
$config['csrf_token_name'] = 'csrf_test_name';
$config['csrf_cookie_name'] = 'csrf_cookie_name';
$config['csrf_expire'] = 7200;
$config['csrf_regenerate'] = TRUE;
$config['csrf_exclude_uris'] = array();

/*
|--------------------------------------------------------------------------
| Output Compression
|--------------------------------------------------------------------------
|
| Enables Gzip output compression for faster page loads.  When enabled,
| the output class will test whether your server supports Gzip.
| Even if it does, however, not all browsers support compression
| so enable only if you are reasonably sure your visitors can handle it.
|
| Only used if zlib.output_compression is turned off in your php.ini.
| Please do not use it together with httpd-level output compression.
|
| VERY IMPORTANT:  If you are getting a blank page when compression is enabled it
| means you are prematurely outputting something to your browser. It could
| even be a line of whitespace at the end of one of your scripts.  For
| compression to work, nothing can be sent before the output buffer is called
| by the output class.  Do not 'echo' any values with compression enabled.
|
*/
$config['compress_output'] = FALSE;

/*
|--------------------------------------------------------------------------
| Master Time Reference
|--------------------------------------------------------------------------
|
| Options are 'local' or any PHP supported timezone. This preference tells
| the system whether to use your server's local time as the master 'now'
| reference, or convert it to the configured one timezone. See the 'date
| helper' page of the user guide for information regarding date handling.
|
*/
$config['time_reference'] = 'local';

/*
|--------------------------------------------------------------------------
| Rewrite PHP Short Tags
|--------------------------------------------------------------------------
|
| If your PHP installation does not have short tag support enabled CI
| can rewrite the tags on-the-fly, enabling you to utilize that syntax
| in your view files.  Options are TRUE or FALSE (boolean)
|
| Note: You need to have eval() enabled for this to work.
|
*/
$config['rewrite_short_tags'] = FALSE;

/*
|--------------------------------------------------------------------------
| Reverse Proxy IPs
|--------------------------------------------------------------------------
|
| If your server is behind a reverse proxy, you must whitelist the proxy
| IP addresses from which CodeIgniter should trust headers such as
| HTTP_X_FORWARDED_FOR and HTTP_CLIENT_IP in order to properly identify
| the visitor's IP address.
|
| You can use both an array or a comma-separated list of proxy addresses,
| as well as specifying whole subnets. Here are a few examples:
|
| Comma-separated:	'10.0.1.200,192.168.5.0/24'
| Array:		array('10.0.1.200', '192.168.5.0/24')
*/
$config['proxy_ips'] = '';

$config['daigou'] = '代购,香港,HK,Hong Kong,hk';

$config['at'] = '关注,好友,添加';

$config['news'] = '资讯,news,NEWS';

$config['express_list'] = array (
  'auspost' => '澳大利亚邮政',
  'aae' => 'AAE',
  'anxindakuaixi' => '安信达',
  'huitongkuaidi' => '汇通快运',
  'baifudongfang' => '百福东方',
  'bht' => 'BHT',
  'youzhengguonei' => '邮政小包（国内），邮政包裹（国内）、邮政国内给据（国内）',
  'bangsongwuliu' => '邦送物流',
  'cces' => '希伊艾斯',
  'coe' => '中国东方',
  'chuanxiwuliu' => '传喜物流',
  'canpost' => '加拿大邮政Canada Post',
  'canpostfr' => '加拿大邮政Canada Post',
  'datianwuliu' => '大田物流',
  'debangwuliu' => '德邦物流',
  'dpex' => 'DPEX',
  'dhl' => 'DHL-中国件',
  'dhlen' => 'DHL-国际件',
  'dhlde' => 'DHL-德国件',
  'dsukuaidi' => 'D速快递',
  'disifang' => '递四方',
  'ems' => 'E邮宝',
  'emsen' => 'EMS',
  'emsguoji' => 'EMS国际-中文',
  'emsinten' => 'EMS国际-英文',
  'fedex' => 'Fedex-国际件',
  'fedexcn' => 'Fedex',
  'fedexus' => 'Fedex',
  'feikangda' => '飞康达物流',
  'feikuaida' => '飞快达',
  'rufengda' => '如风达快递',
  'fengxingtianxia' => '风行天下',
  'feibaokuaidi' => '飞豹快递',
  'ganzhongnengda' => '港中能达',
  'guotongkuaidi' => '国通快递',
  'guangdongyouzhengwuliu' => '广东邮政',
  'youzhengguoji' => '邮政小包（国际），邮政包裹（国际）、邮政国内给据（国际）',
  'gls' => 'GLS',
  'gongsuda' => '共速达',
  'huiqiangkuaidi' => '汇强快递',
  'tiandihuayu' => '天地华宇',
  'hengluwuliu' => '恒路物流',
  'huaxialongwuliu' => '华夏龙',
  'tiantian' => '天天快递',
  'haiwaihuanqiu' => '海外环球',
  'hebeijianhua' => '河北建华',
  'haimengsudi' => '海盟速递',
  'huaqikuaiyun' => '华企快运',
  'haihongwangsong' => '山东海红',
  'jiajiwuliu' => '佳吉物流',
  'jiayiwuliu' => '佳怡物流',
  'jiayunmeiwuliu' => '加运美',
  'jinguangsudikuaijian' => '京广速递',
  'jixianda' => '急先达',
  'jinyuekuaidi' => '晋越快递',
  'jietekuaidi' => '捷特快递',
  'jindawuliu' => '金大物流',
  'jialidatong' => '嘉里大通',
  'kuaijiesudi' => '快捷速递',
  'kangliwuliu' => '康力物流',
  'kuayue' => '跨越物流',
  'lianhaowuliu' => '联昊通',
  'longbanwuliu' => '龙邦物流',
  'lanbiaokuaidi' => '蓝镖快递',
  'lejiedi' => '乐捷递',
  'lianbangkuaidi' => '联邦快递',
  'lianbangkuaidien' => '联邦快递',
  'lijisong' => '立即送',
  'longlangkuaidi' => '隆浪快递',
  'menduimen' => '门对门',
  'meiguokuaidi' => '美国快递',
  'mingliangwuliu' => '明亮物流',
  'ocs' => 'OCS',
  'ontrac' => 'onTrac',
  'quanchenkuaidi' => '全晨快递',
  'quanjitong' => '全际通',
  'quanritongkuaidi' => '全日通',
  'quanyikuaidi' => '全一快递',
  'quanfengkuaidi' => '全峰快递',
  'sevendays' => '七天连锁',
  'shentong' => '申通',
  'shunfeng' => '顺丰',
  'shunfengen' => '顺丰',
  'santaisudi' => '三态速递',
  'shenghuiwuliu' => '盛辉物流',
  'suer' => '速尔物流',
  'shengfengwuliu' => '盛丰物流',
  'shangda' => '上大物流',
  'saiaodi' => '赛澳递',
  'sxhongmajia' => '山西红马甲',
  'shenganwuliu' => '圣安物流',
  'suijiawuliu' => '穗佳物流',
  'tnt' => 'TNT',
  'tnten' => 'TNT',
  'tonghetianxia' => '通和天下',
  'ups' => 'UPS',
  'upsen' => 'UPS',
  'youshuwuliu' => '优速物流',
  'usps' => 'USPS',
  'wanjiawuliu' => '万家物流',
  'wanxiangwuliu' => '万象物流',
  'weitepai' => '微特派',
  'xinbangwuliu' => '新邦物流',
  'xinfengwuliu' => '信丰物流',
  'xingchengjibian' => '星晨急便',
  'xinhongyukuaidi' => '鑫飞鸿',
  'neweggozzo' => '新蛋奥硕物流',
  'hkpost' => '香港邮政',
  'yuantong' => '圆通速递',
  'yunda' => '韵达快运',
  'yuntongkuaidi' => '运通快递',
  'yuanchengwuliu' => '远成物流',
  'yafengsudi' => '亚风速递',
  'yibangwuliu' => '一邦速递',
  'yuanweifeng' => '源伟丰快递',
  'yuanzhijiecheng' => '元智捷诚',
  'yuefengwuliu' => '越丰物流',
  'yuananda' => '源安达',
  'yuanfeihangwuliu' => '原飞航',
  'zhongxinda' => '忠信达',
  'zhimakaimen' => '芝麻开门',
  'yinjiesudi' => '银捷速递',
  'yitongfeihong' => '一统飞鸿',
  'zhongtong' => '中通速递',
  'zhaijisong' => '宅急送',
  'zhongyouwuliu' => '中邮物流',
  'zhongsukuaidi' => '中速快件',
  'zhengzhoujianhua' => '郑州建华',
  'zhongtianwanyun' => '中天万运',
);

$config['city'] = array (
  101010100 => '北京',
  101010300 => '朝阳',
  101010400 => '顺义',
  101010500 => '怀柔',
  101010600 => '通州',
  101010700 => '昌平',
  101010800 => '延庆',
  101010900 => '丰台',
  101011000 => '石景山',
  101011100 => '大兴',
  101011200 => '房山',
  101011300 => '密云',
  101011400 => '门头沟',
  101011500 => '平谷',
  101011600 => '八达岭',
  101011700 => '佛爷顶',
  101011800 => '汤河口',
  101011900 => '密云上甸子',
  101012000 => '斋堂',
  101012100 => '霞云岭',
  101012200 => '北京城区',
  101010200 => '海淀',
  101030100 => '天津',
  101030300 => '宝坻',
  101030400 => '东丽',
  101030500 => '西青',
  101030600 => '北辰',
  101031400 => '蓟县',
  101030800 => '汉沽',
  101030900 => '静海',
  101031000 => '津南',
  101031100 => '塘沽',
  101031200 => '大港',
  101030200 => '武清',
  101030700 => '宁河',
  101020100 => '上海',
  101020300 => '宝山',
  101020500 => '嘉定',
  101020600 => '南汇',
  101021300 => '浦东',
  101020800 => '青浦',
  101020900 => '松江',
  101021000 => '奉贤',
  101021100 => '崇明',
  101021200 => '徐家汇',
  101020200 => '闵行',
  101020700 => '金山',
  101090101 => '石家庄',
  101090301 => '张家口',
  101090402 => '承德',
  101090501 => '唐山',
  101091101 => '秦皇岛',
  101090701 => '沧州',
  101090801 => '衡水',
  101090901 => '邢台',
  101091001 => '邯郸',
  101090201 => '保定',
  101090601 => '廊坊',
  101180101 => '郑州',
  101180301 => '新乡',
  101180401 => '许昌',
  101180501 => '平顶山',
  101180601 => '信阳',
  101180701 => '南阳',
  101180801 => '开封',
  101180901 => '洛阳',
  101181001 => '商丘',
  101181101 => '焦作',
  101181201 => '鹤壁',
  101181301 => '濮阳',
  101181401 => '周口',
  101181501 => '漯河',
  101181601 => '驻马店',
  101181701 => '三门峡',
  101181801 => '济源',
  101180201 => '安阳',
  101220101 => '合肥',
  101220301 => '芜湖',
  101220401 => '淮南',
  101220501 => '马鞍山',
  101220601 => '安庆',
  101220701 => '宿州',
  101220801 => '阜阳',
  101220901 => '亳州',
  101221001 => '黄山',
  101221101 => '滁州',
  101221201 => '淮北',
  101221301 => '铜陵',
  101221401 => '宣城',
  101221501 => '六安',
  101221601 => '巢湖',
  101221701 => '池州',
  101220201 => '蚌埠',
  101210101 => '杭州',
  101211101 => '舟山',
  101210201 => '湖州',
  101210301 => '嘉兴',
  101210901 => '金华',
  101210501 => '绍兴',
  101210601 => '台州',
  101210701 => '温州',
  101210801 => '丽水',
  101211001 => '衢州',
  101210401 => '宁波',
  101040100 => '重庆',
  101040300 => '合川',
  101040400 => '南川',
  101040500 => '江津',
  101040600 => '万盛',
  101040700 => '渝北',
  101040800 => '北碚',
  101040900 => '巴南',
  101041000 => '长寿',
  101041100 => '黔江',
  101041200 => '万州天城',
  101041300 => '万州龙宝',
  101041400 => '涪陵',
  101041500 => '开县',
  101041600 => '城口',
  101041700 => '云阳',
  101041800 => '巫溪',
  101041900 => '奉节',
  101042000 => '巫山',
  101042100 => '潼南',
  101042200 => '垫江',
  101042300 => '梁平',
  101042400 => '忠县',
  101042500 => '石柱',
  101042600 => '大足',
  101042700 => '荣昌',
  101042800 => '铜梁',
  101042900 => '璧山',
  101043000 => '丰都',
  101043100 => '武隆',
  101043200 => '彭水',
  101043300 => '綦江',
  101043400 => '酉阳',
  101043600 => '秀山',
  101043700 => '沙坪坝',
  101040200 => '永川',
  101230101 => '福州',
  101230501 => '泉州',
  101230601 => '漳州',
  101230701 => '龙岩',
  101230509 => '晋江',
  101230901 => '南平',
  101230201 => '厦门',
  101230301 => '宁德',
  101230401 => '莆田',
  101230801 => '三明',
  101160101 => '兰州',
  101160301 => '平凉',
  101160401 => '庆阳',
  101160501 => '武威',
  101160601 => '金昌',
  101161401 => '嘉峪关',
  101160801 => '酒泉',
  101160901 => '天水',
  101161001 => '武都',
  101161101 => '临夏',
  101161201 => '合作',
  101161301 => '白银',
  101160201 => '定西',
  101160701 => '张掖',
  101280101 => '广州',
  101280301 => '惠州',
  101280401 => '梅州',
  101280501 => '汕头',
  101280601 => '深圳',
  101280701 => '珠海',
  101280800 => '佛山',
  101280901 => '肇庆',
  101281001 => '湛江',
  101281101 => '江门',
  101281201 => '河源',
  101281301 => '清远',
  101281401 => '云浮',
  101281501 => '潮州',
  101281601 => '东莞',
  101281701 => '中山',
  101281801 => '阳江',
  101281901 => '揭阳',
  101282001 => '茂名',
  101282101 => '汕尾',
  101280201 => '韶关',
  101300101 => '南宁',
  101300301 => '柳州',
  101300401 => '来宾',
  101300501 => '桂林',
  101300601 => '梧州',
  101301401 => '防城港',
  101300801 => '贵港',
  101300901 => '玉林',
  101301001 => '百色',
  101301101 => '钦州',
  101301201 => '河池',
  101301301 => '北海',
  101300201 => '崇左',
  101300701 => '贺州',
  101260101 => '贵阳',
  101260301 => '安顺',
  101260401 => '都匀',
  101260906 => '兴义',
  101260601 => '铜仁',
  101260701 => '毕节',
  101260801 => '六盘水',
  101260201 => '遵义',
  101260501 => '凯里',
  101290101 => '昆明',
  101290301 => '红河',
  101290601 => '文山',
  101290701 => '玉溪',
  101290801 => '楚雄',
  101290901 => '普洱',
  101291001 => '昭通',
  101291101 => '临沧',
  101291201 => '怒江',
  101291301 => '香格里拉',
  101291401 => '丽江',
  101291501 => '德宏',
  101291601 => '景洪',
  101290201 => '大理',
  101290401 => '曲靖',
  101290501 => '保山',
  101080101 => '呼和浩特',
  101080301 => '乌海',
  101080401 => '集宁',
  101080501 => '通辽',
  101081201 => '阿拉善左旗',
  101080701 => '鄂尔多斯',
  101080801 => '临河',
  101080901 => '锡林浩特',
  101081000 => '呼伦贝尔',
  101081101 => '乌兰浩特',
  101080201 => '包头',
  101080601 => '赤峰',
  101240101 => '南昌',
  101240301 => '上饶',
  101240401 => '抚州',
  101240501 => '宜春',
  101241101 => '鹰潭',
  101240701 => '赣州',
  101240801 => '景德镇',
  101240901 => '萍乡',
  101241001 => '新余',
  101240201 => '九江',
  101240601 => '吉安',
  101200101 => '武汉',
  101200501 => '黄冈',
  101200801 => '荆州',
  101200901 => '宜昌',
  101201001 => '恩施',
  101201101 => '十堰',
  101201201 => '神农架',
  101201301 => '随州',
  101201401 => '荆门',
  101201501 => '天门',
  101201601 => '仙桃',
  101201701 => '潜江',
  101200201 => '襄樊',
  101200301 => '鄂州',
  101200401 => '孝感',
  101200601 => '黄石',
  101200701 => '咸宁',
  101270101 => '成都',
  101270301 => '自贡',
  101270401 => '绵阳',
  101270501 => '南充',
  101270601 => '达州',
  101270701 => '遂宁',
  101270801 => '广安',
  101270901 => '巴中',
  101271001 => '泸州',
  101271101 => '宜宾',
  101271201 => '内江',
  101271301 => '资阳',
  101271401 => '乐山',
  101271501 => '眉山',
  101271601 => '凉山',
  101271701 => '雅安',
  101271801 => '甘孜',
  101271901 => '阿坝',
  101272001 => '德阳',
  101272101 => '广元',
  101270201 => '攀枝花',
  101170101 => '银川',
  101170501 => '中卫',
  101170401 => '固原',
  101170201 => '石嘴山',
  101170301 => '吴忠',
  101150101 => '西宁',
  101150301 => '黄南',
  101150801 => '海北',
  101150501 => '果洛',
  101150601 => '玉树',
  101150701 => '海西',
  101150201 => '海东',
  101150401 => '海南',
  101120101 => '济南',
  101120601 => '潍坊',
  101120901 => '临沂',
  101121001 => '菏泽',
  101121101 => '滨州',
  101121201 => '东营',
  101121301 => '威海',
  101121401 => '枣庄',
  101121501 => '日照',
  101121601 => '莱芜',
  101121701 => '聊城',
  101120201 => '青岛',
  101120301 => '淄博',
  101120401 => '德州',
  101120501 => '烟台',
  101120701 => '济宁',
  101120801 => '泰安',
  101110101 => '西安',
  101110300 => '延安',
  101110401 => '榆林',
  101111001 => '铜川',
  101110601 => '商洛',
  101110701 => '安康',
  101110801 => '汉中',
  101110901 => '宝鸡',
  101110200 => '咸阳',
  101110501 => '渭南',
  101100101 => '太原',
  101100701 => '临汾',
  101100801 => '运城',
  101100901 => '朔州',
  101101001 => '忻州',
  101100501 => '长治',
  101100201 => '大同',
  101100301 => '阳泉',
  101100401 => '晋中',
  101100601 => '晋城',
  101101100 => '吕梁',
  101130101 => '乌鲁木齐',
  101130301 => '石河子',
  101130401 => '昌吉',
  101130501 => '吐鲁番',
  101130601 => '库尔勒',
  101130701 => '阿拉尔',
  101130801 => '阿克苏',
  101130901 => '喀什',
  101131001 => '伊宁',
  101131101 => '塔城',
  101131201 => '哈密',
  101131301 => '和田',
  101131401 => '阿勒泰',
  101131501 => '阿图什',
  101131601 => '博乐',
  101130201 => '克拉玛依',
  101140101 => '拉萨',
  101140301 => '山南',
  101140701 => '阿里',
  101140501 => '昌都',
  101140601 => '那曲',
  101140201 => '日喀则',
  101140401 => '林芝',
  101340101 => '台北县',
  101340201 => '高雄',
  101340401 => '台中',
  101310101 => '海口',
  101310201 => '三亚',
  101310202 => '东方',
  101310203 => '临高',
  101310204 => '澄迈',
  101310205 => '儋州',
  101310206 => '昌江',
  101310207 => '白沙',
  101310208 => '琼中',
  101310209 => '定安',
  101310210 => '屯昌',
  101310211 => '琼海',
  101310212 => '文昌',
  101310214 => '保亭',
  101310215 => '万宁',
  101310216 => '陵水',
  101310217 => '西沙',
  101310220 => '南沙岛',
  101310221 => '乐东',
  101310222 => '五指山',
  101310102 => '琼山',
  101250101 => '长沙',
  101250301 => '株洲',
  101250401 => '衡阳',
  101250501 => '郴州',
  101250601 => '常德',
  101250700 => '益阳',
  101250801 => '娄底',
  101250901 => '邵阳',
  101251001 => '岳阳',
  101251101 => '张家界',
  101251201 => '怀化',
  101251301 => '黔阳',
  101251401 => '永州',
  101251501 => '吉首',
  101250201 => '湘潭',
  101190101 => '南京',
  101190301 => '镇江',
  101190401 => '苏州',
  101190501 => '南通',
  101190601 => '扬州',
  101191301 => '宿迁',
  101190801 => '徐州',
  101190901 => '淮安',
  101191001 => '连云港',
  101191101 => '常州',
  101191201 => '泰州',
  101190201 => '无锡',
  101190701 => '盐城',
  101050101 => '哈尔滨',
  101050301 => '牡丹江',
  101050401 => '佳木斯',
  101050501 => '绥化',
  101050601 => '黑河',
  101051301 => '双鸭山',
  101050801 => '伊春',
  101050901 => '大庆',
  101051002 => '七台河',
  101051101 => '鸡西',
  101051201 => '鹤岗',
  101050201 => '齐齐哈尔',
  101050701 => '大兴安岭',
  101060101 => '长春',
  101060301 => '延吉',
  101060401 => '四平',
  101060901 => '白山',
  101060601 => '白城',
  101060701 => '辽源',
  101060801 => '松原',
  101060201 => '吉林',
  101060501 => '通化',
  101070101 => '沈阳',
  101070301 => '鞍山',
  101070401 => '抚顺',
  101070501 => '本溪',
  101070601 => '丹东',
  101071401 => '葫芦岛',
  101070801 => '营口',
  101070901 => '阜新',
  101071001 => '辽阳',
  101071101 => '铁岭',
  101071201 => '朝阳',
  101071301 => '盘锦',
  101070201 => '大连',
  101070701 => '锦州',
);